version: "3.9"

services:
  db:
    image: postgres:16
    container_name: banxedien_db
    restart: always
    environment:
      POSTGRES_DB: GIS_BANXEDIEN
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: banxedien_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: GIS_BANXEDIEN
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    build: ./frontend
    container_name: banxedien_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
